import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.164.1/examples/jsm/controls/OrbitControls.js';

const canvas = document.querySelector('#world');
const scene = new THREE.Scene(); scene.background = new THREE.Color(0xffffff);
const camera = new THREE.PerspectiveCamera(42, innerWidth/innerHeight, .1, 150);
camera.position.set(11, 12, 14);
const renderer = new THREE.WebGLRenderer({canvas, antialias:true}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true;
const controls = new OrbitControls(camera, canvas); controls.target.set(0,0,0); controls.enableDamping=true; controls.maxPolarAngle=Math.PI*.48; controls.minDistance=7;controls.maxDistance=34;
scene.add(new THREE.HemisphereLight(0xffffff,0xcbd9d5,2.6)); const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(8,14,6);sun.castShadow=true;scene.add(sun);

const plate = new THREE.Group(); scene.add(plate); const placed=[]; const raycaster=new THREE.Raycaster(); const pointer=new THREE.Vector2();
const material = c => new THREE.MeshStandardMaterial({color:c,roughness:.31,metalness:.04});
function roundedBox(w,h,d,r=.12){const s=new THREE.Shape();const x=-w/2,z=-d/2;s.moveTo(x+r,z);s.lineTo(x+w-r,z);s.quadraticCurveTo(x+w,z,x+w,z+r);s.lineTo(x+w,z+d-r);s.quadraticCurveTo(x+w,z+d,x+w-r,z+d);s.lineTo(x+r,z+d);s.quadraticCurveTo(x,z+d,x,z+d-r);s.lineTo(x,z+r);s.quadraticCurveTo(x,z,x+r,z);return new THREE.ExtrudeGeometry(s,{depth:h,bevelEnabled:true,bevelSegments:2,bevelSize:r*.32,bevelThickness:r*.32});}
const base = new THREE.Mesh(roundedBox(15,.32,15,.18),material('#b7dfcf'));base.rotation.x=-Math.PI/2;base.position.y=-.32;base.receiveShadow=true;plate.add(base);
const studGeo=new THREE.CylinderGeometry(.18,.18,.09,18);const plateMat=material('#9ecdbd');for(let x=-7;x<=7;x++)for(let z=-7;z<=7;z++){const stud=new THREE.Mesh(studGeo,plateMat);stud.position.set(x*.92,0,z*.92);stud.castShadow=true;plate.add(stud)}
const colors=[['Red','#ef4b4f'],['Coral','#ff826f'],['Orange','#ff9c3c'],['Yellow','#ffd54d'],['Lime','#a8d847'],['Green','#4dbd88'],['Teal','#36b9b0'],['Blue','#559be5'],['Purple','#a774d8'],['Pink','#f28baf'],['White','#f7f7f2'],['Black','#27343a']];
const pieces=[{name:'Classic 2 × 4',x:2,z:4,h:1},{name:'Brick 2 × 2',x:2,z:2,h:1},{name:'Flat 2 × 4',x:2,z:4,h:.38},{name:'Brick 1 × 4',x:1,z:4,h:1},{name:'Slope 2 × 2',x:2,z:2,h:1},{name:'Round 2 × 2',x:2,z:2,h:1}];
let selectedPiece=pieces[0],selectedColor=colors[0],rotation=0,mode='orbit',activeFilter='All';
function brickMesh(piece,color){ const group=new THREE.Group(),unit=.92,w=piece.x*unit-.06,d=piece.z*unit-.06,h=piece.h*.9;let body;
 if(piece.name.startsWith('Round')) body=new THREE.Mesh(new THREE.CylinderGeometry(w/2,w/2,h,28),material(color)); else {body=new THREE.Mesh(roundedBox(w,h,d,.09),material(color));body.rotation.x=-Math.PI/2;body.position.y=-h/2}
 body.castShadow=true;body.receiveShadow=true;group.add(body); const countX=piece.x,countZ=piece.z;for(let x=0;x<countX;x++)for(let z=0;z<countZ;z++){let st=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.1,18),material(color));st.position.set((x-(countX-1)/2)*unit,h*.05,(z-(countZ-1)/2)*unit);st.castShadow=true;group.add(st)} group.userData={piece,color,height:h};return group; }
function addBrick(pos){const b=brickMesh(selectedPiece,selectedColor[1]);b.position.set(Math.round(pos.x/.92)*.92,findHeight(pos)+.02,Math.round(pos.z/.92)*.92);b.rotation.y=rotation;b.userData.height=selectedPiece.h*.9;b.userData.footprint={x:selectedPiece.x,z:selectedPiece.z};scene.add(b);placed.push(b);updateCount();}
function findHeight(p){let height=0;placed.forEach(b=>{const dx=Math.abs(b.position.x-p.x),dz=Math.abs(b.position.z-p.z);if(dx<1.2&&dz<1.2)height=Math.max(height,b.position.y+b.userData.height*.52)});return height+.48}
function updateCount(){document.querySelector('#count').textContent=placed.length}
function buildUI(){const filters=document.querySelector('#colorFilters');filters.innerHTML=['All',...colors.map(x=>x[0])].map(n=>`<button class="filter ${n===activeFilter?'active':''}" data-color="${n}">${n==='All'?'All':`<i style="background:${colors.find(c=>c[0]===n)[1]}"></i>${n}`}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.color;buildUI()});
 const grid=document.querySelector('#brickGrid'), search=document.querySelector('#colorSearch').value.toLowerCase();grid.innerHTML=pieces.map((p,i)=>{const c=selectedColor[1];return `<button class="brick-card ${p===selectedPiece?'active':''}" data-index="${i}" draggable="true"><div class="mini-piece" style="background:${c};width:${Math.min(100,p.z*25)}%"></div><b>${p.name}</b><small>${p.x*p.z} studs</small></button>`}).join('');grid.querySelectorAll('.brick-card').forEach(el=>{el.onclick=()=>{selectedPiece=pieces[+el.dataset.index];syncSelected();buildUI()};el.addEventListener('dragstart',e=>{selectedPiece=pieces[+el.dataset.index];syncSelected();e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('text/plain',el.dataset.index);document.body.classList.add('dragging')});el.addEventListener('dragend',()=>document.body.classList.remove('dragging'))}); if(search){const match=colors.find(c=>c[0].toLowerCase().includes(search));if(match&&match!==selectedColor){selectedColor=match;syncSelected();buildUI()}}}
function syncSelected(){document.querySelector('#selectedName').textContent=selectedPiece.name;document.querySelector('#selectedInfo').textContent=`${selectedPiece.x*selectedPiece.z} studs · ${selectedColor[0]}`;document.querySelector('#selectedPreview').style.background=selectedColor[1]}
document.querySelector('#colorSearch').addEventListener('input',buildUI); buildUI();syncSelected();
function setMode(next){mode=next;document.body.className=next;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));controls.enabled=next==='orbit';const titles={orbit:['Orbit build-view','Swipe or drag to orbit · Scroll to zoom · Click the baseplate to build'],free:['Free-cam build-view','Use the on-screen joystick to glide around · Click to build'],person:['Person-view','Use WASD to explore your build · Click to place a brick']};document.querySelector('#modeTitle').textContent=titles[next][0];document.querySelector('#modeHelp').textContent=titles[next][1];if(next==='person'){camera.position.set(0,2.2,11);camera.lookAt(0,1,0)}showToast(next==='person'?'Person-view activated — WASD to walk':'Camera mode changed')}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelector('#undoButton').onclick=()=>{const b=placed.pop();if(b){scene.remove(b);updateCount();showToast('Last brick removed')}};document.querySelector('#clearButton').onclick=()=>{placed.forEach(b=>scene.remove(b));placed.length=0;updateCount();showToast('Baseplate cleared')};
function getHits(e){const r=canvas.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects([base,...placed],true)}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(mode==='orbit'&&e.button!==0)return;if(e.button===2){const hit=getHits(e).find(h=>h.object.parent?.userData?.piece);const group=hit?.object.parent;if(group){scene.remove(group);placed.splice(placed.indexOf(group),1);updateCount()}return}canvas.dataset.dragX=e.clientX;canvas.dataset.dragY=e.clientY});canvas.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-canvas.dataset.dragX,e.clientY-canvas.dataset.dragY)>6)return;const hits=getHits(e);if(!hits.length)return;const h=hits[0];let p=h.point;if(h.object===base||h.object.parent===plate)addBrick(p);else {let g=h.object.parent;while(g.parent!==scene)g=g.parent;addBrick(g.position)} });
canvas.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';document.body.classList.add('dragging')});canvas.addEventListener('dragleave',e=>{if(e.relatedTarget!==canvas)document.body.classList.remove('dragging')});canvas.addEventListener('drop',e=>{e.preventDefault();const index=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(index)&&pieces[index]){selectedPiece=pieces[index];syncSelected();buildUI()}const hit=getHits(e)[0];if(hit){if(hit.object===base||hit.object.parent===plate)addBrick(hit.point);else {let g=hit.object.parent;while(g.parent!==scene)g=g.parent;addBrick(g.position)}showToast(`${selectedPiece.name} added`)}document.body.classList.remove('dragging')});
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'){rotation+=Math.PI/2;showToast('Piece rotated')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z')document.querySelector('#undoButton').click()});
let joystick={x:0,y:0},joyActive=false;const joy=document.querySelector('.joystick-base'),knob=document.querySelector('#joystickKnob');joy.addEventListener('pointerdown',e=>{joyActive=true;joy.setPointerCapture(e.pointerId)});joy.addEventListener('pointermove',e=>{if(!joyActive)return;const r=joy.getBoundingClientRect(),x=Math.max(-28,Math.min(28,e.clientX-r.left-50)),y=Math.max(-28,Math.min(28,e.clientY-r.top-50));knob.style.transform=`translate(${x}px,${y}px)`;joystick={x:x/28,y:y/28}});joy.addEventListener('pointerup',()=>{joyActive=false;joystick={x:0,y:0};knob.style.transform=''});
const keys={};addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);function movePerson(){if(mode==='free'&&(joystick.x||joystick.y)){camera.position.x+=joystick.x*.08;camera.position.z+=joystick.y*.08;controls.target.x+=joystick.x*.08;controls.target.z+=joystick.y*.08}if(mode==='person'){const speed=.1;if(keys.w)camera.position.z-=speed;if(keys.s)camera.position.z+=speed;if(keys.a)camera.position.x-=speed;if(keys.d)camera.position.x+=speed;camera.lookAt(camera.position.x,camera.position.y,camera.position.z-8)}}
function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),1800)}
function loop(){requestAnimationFrame(loop);movePerson();controls.update();renderer.render(scene,camera)}loop();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
